export const TYPE_SELECTED = {
  grass: false,
  normal: false,
  fighting: false,
  flying: false,
  poison: false,
  ground: false,
  rock: false,
  bug: false,
  ghost: false,
  steel: false,
  fire: false,
  water: false,
  electric: false,
  psychic: false,
  ice: false,
  dragon: false,
  dark: false,
  fairy: false,
  unknown: false,
  shadow: false,
};
